### ISSUE TITLE
Create a common client utility module or package

### ISSUE THREAD

**Issue by prakashngit** [hyperledger-labs/private-data-objects#171]
Several common methods used by the client in test-request, test-cotract, pdo-udpate, pdo-create, pdo-shell. We can collect all of these in a common client utility module or package.

**Comment by cmickeyb** [comment]
I don't think this should be a goal. Each of the clients that we have (the python/pdo/test/*, the update/create scripts, pdo-shell, and auction test) use different flows in "how" and "when" pieces of the flow are constructed and used. for example, test-request and test-contract must accommodate direct connection of the pservice and eservice. This code could not be shared with any of the other clients.  The auction test is also distinct because it has to manage so many different identities. Again... the high level pattern may be similar, but there is no code that can be easily shared.

**Comment by prakashngit** [comment]
This (and more) has been accomplished with the new shell modules.
