### ISSUE TITLE
Determine whether the hash of the contract should include the compilation report

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/private-data-objects#294]
The hash of the contract code (see [here](https://github.com/hyperledger-labs/private-data-objects/blob/73f6f9f4156f0cec9616ec6260fea1ff0d2adde2/eservice/lib/libpdo_enclave/contract_code.cpp#L187)) currently includes the compilation report.
From the conversation [here](https://github.com/hyperledger-labs/private-data-objects/pull/286#discussion_r461212598), it is not clear that this adds any benefit. The reason is that the compilation report carries a signature of the contract code, and it is therefore already bound to the contract code itself.

**Comment by cmickeyb** [comment]
The problem with removing this is that the reverse is not true. Since we record the code hash in the ledger we could not ensure that the compilation report is used. Suggestion: the compilation report contains the hash of the code, but we hash the contract code object and put that information into the ledger. That is... we keep the behavior as defined & rename the fields.

**Comment by cmickeyb** [comment]
@marcelamelara do we need this one any more? Its part of the old aot code. We don't have support for compilation reports.
